### ISSUE TITLE
testing deployment

### ISSUE THREAD

**Issue by lenzai** [coderbunker/coderbunker-fcc#2]
- console displays running on port 1234 when it is actually 3000
- no error message when Google API key is missing
- no information / log about spider is running when launching blank application
- no visual feedback when clicking `update users`
-

**Comment by mattermoran** [comment]
1. Yeah technically it's correct backend is running on 1234 while UI runs on 3000. I will specify it.
2.  It shows in the console but I will display it on the page too.
3. Not sure what spider are you talking about.
4. Will do

**Comment by mattermoran** [comment]
done in https://github.com/coderbunker/coderbunker-fcc/pull/4
